# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-13 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181213_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='isselect',
            field=models.BooleanField(default=True),
        ),
    ]
